### PR TITLE
Fix obsolete vernacular syntax for locality.

### PR DESCRIPTION
**Pull request by maximedenes**
It was emitting a deprecation warning and will soon be removed from Coq.

@spitters There are many other deprecation warnings emitted when compiling Corn. Is there any plan to fix those?

### CODE REVIEW

**Comment by spitters** [comment]
Thanks! I'll merge when travis is happy.
Travis is failing because travis.yml is missing. @Zimmi48 Didn't we set this up?

I haven't had the time to look into the deprecation warnings. Do you know what's happening?

**Comment by Zimmi48** [comment]
We set it up in #44 but this wasn't merged yet because it was waiting for math-classes to be in OPAM. I've just relaunched the build of #44 so I think it should pass this time and be merged, then we can re-test the present PR.

**Comment by spitters** [comment]
@maximedenes Could you rebase on top of #44, which I just merged. Then we can check that Travis is happy.

**Comment by maximedenes** [comment]
Rebased!

**Comment by Zimmi48** [comment]
The build timed out. Probably worth simply relaunching. The previous builds ran in about 45 minutes so it's easy to go over the limit in case Travis is overloaded.

**Comment by spitters** [comment]
I restarted the build.
Did any of the Coq devs look at incremental compilation for Coq yet?
https://www.cs.utexas.edu/~celik/papers/CelikETAL17iCoq.pdf

**Comment by spitters** [comment]
http://cozy.ece.utexas.edu/icoq/
@ahmet-celik

**Comment by spitters** [comment]
Not sure what this means.

```
$ opam repo -y add coq-released https://coq.inria.fr/opam/released

[ERROR] coq-released is already a remote repository
```

**Comment by Zimmi48** [comment]
@spitters I guess this has happened before since the other open PR on this repository attempts to fix this, see here: https://github.com/c-corn/corn/pull/34/files.
I guess you should just merge this other PR (or ping @JasonGross if you think there is a better solution). In any case, beware that you'd need to change the base branch from v8.5 to master before merging (you can do this with the edit button next to the PR title).

**Comment by spitters** [comment]
OK. I have merged #34 now and applied this by hand to the master branch.
@maximedenes do you want to rebase again, or shall I just pull your request?

**Comment by Zimmi48** [comment]
@spitters You can also close / reopen the PR to trigger a Travis build with a new merge point.

**Comment by maximedenes** [comment]
I'll rebase, it should take only a minute.

**Comment by maximedenes** [comment]
Rebased! :)

**Pull request merged**
