### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by Zimmi48**
Adds the `.travis.yml` configuration file to the master branch. Normally, it should be enough but let Travis confirm this.

### CODE REVIEW

**Comment by Zimmi48** [comment]
The Travis build is failing because the Opam package for math classes is broken. I suggest you do a new release of math classes so that we can produce a corresponding Opam package that is compatible with 8.7.0.

**Comment by spitters** [comment]
@Zimmi48 Thanks.
https://github.com/coq/opam-coq-archive/pull/213

I guess that when we have corn fixed, I should do the same for corn opam.

**Comment by Zimmi48** [comment]
Indeed.

**Comment by Zimmi48** [comment]
Closing / reopening to relaunch Travis.

**Comment by Zimmi48** [comment]
Travis is still failing because the update to https://github.com/coq/opam-coq-archive haven't been propagated to https://coq.inria.fr/opam/released yet. I don't know how long this usually takes.

**Comment by Zimmi48** [comment]
Travis passed, so this is ready to merge.

**Comment by spitters** [comment]
@Zimmi48 Thanks!

**Pull request merged**
